[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 100
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 4
  wrap_comments = true

remappings = [
"ds-test/=lib/forge-std/lib/ds-test/src/",
"erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
"forge-std/=lib/forge-std/src/",
"openzeppelin-contracts/=lib/openzeppelin-contracts/",
"openzeppelin/=lib/openzeppelin-contracts/contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
